# Generated by Django 4.2.6 on 2023-10-05 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='learner_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField()),
                ('score', models.IntegerField()),
                ('current_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junction.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
