# Generated by Django 4.2.6 on 2023-10-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0003_rename_learner_info_learner_user_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
