# Generated by Django 4.2.6 on 2023-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_learner',
            name='last_achievement',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='acheivement',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
