# Generated by Django 4.2.6 on 2023-10-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0010_rename_rating_course_course_rating_rating_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='message_body',
        ),
        migrations.AddField(
            model_name='messages',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
