# Generated by Django 4.2.6 on 2023-10-06 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0011_rename_message_messages_message_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=20)),
                ('interest_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junction.interests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapitres',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='user_category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='user_category',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junction.course'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junction.course'),
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='chapitres',
        ),
        migrations.DeleteModel(
            name='user_category',
        ),
        migrations.AddField(
            model_name='course',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='junction.interests'),
        ),
    ]
