# Generated by Django 4.2.6 on 2023-10-07 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0013_child_learner_child_score_child_learner_child_streak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child_learner',
            old_name='child_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='child_learner',
            old_name='child_streak',
            new_name='streak',
        ),
        migrations.AddField(
            model_name='child_learner',
            name='current_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='junction.course'),
        ),
    ]
